-- MySQL Script generated by MySQL Workbench
-- 10/08/16 11:00:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rbac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rbac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rbac3` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `rbac3` ;

-- -----------------------------------------------------
-- Table `rbac_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login_id` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login_status` ENUM('yes', 'no') NULL DEFAULT 'no',
  `status` ENUM('active', 'inactive') NULL DEFAULT 'active',
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME NULL,
  `created_by` INT NULL,
  `modified_by` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`login_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_roles` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_actions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_actions` (
  `action_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`action_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_modules` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_modules` (
  `module_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_permissions` (
  `permission_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `module_id` INT UNSIGNED NOT NULL,
  `action_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`),
  INDEX `fk_permissions_module_id_idx` (`module_id` ASC),
  INDEX `fk_permissions_action_id_idx` (`action_id` ASC),
  CONSTRAINT `fk_permissions_module_id`
    FOREIGN KEY (`module_id`)
    REFERENCES `rbac_modules` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissions_action_id`
    FOREIGN KEY (`action_id`)
    REFERENCES `rbac_actions` (`action_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_role_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_role_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_role_permissions` (
  `role_permission_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NOT NULL,
  `permission_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`role_permission_id`),
  INDEX `fk_role_permissions_role_id_idx` (`role_id` ASC),
  INDEX `fk_role_permissions_permission_id_idx` (`permission_id` ASC),
  CONSTRAINT `fk_role_permissions_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `rbac_roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permissions_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `rbac_permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_user_roles` (
  `user_role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_role_id`),
  INDEX `fk_user_roles_role_id_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_roles_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `rbac_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `rbac_roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rbac_custom_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rbac_custom_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rbac_custom_permissions` (
  `custom_permission_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `permission_id` INT UNSIGNED NOT NULL,
  `assigned_by` INT UNSIGNED NOT NULL,
  `status` ENUM('active', 'inactive') NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`custom_permission_id`),
  INDEX `fk_custom_permission_user_id_idx` (`user_id` ASC),
  INDEX `fk_custom_permission_permission_id_idx` (`permission_id` ASC),
  INDEX `fk_custom_permission_assigned_by_idx` (`assigned_by` ASC),
  CONSTRAINT `fk_custom_permission_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `rbac_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custom_permission_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `rbac_permissions` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custom_permission_assigned_by`
    FOREIGN KEY (`assigned_by`)
    REFERENCES `rbac_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
